spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 1234


#mybatis 配置 mapper中  resultType的前缀
mybatis:
  type-aliases-package: com.yangyu.po
  mapper-locations: classpath:com/yangyu/mapper/*Mapper.xml

  #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  #    database-platform: com.yangyu.util.MySQL5InnoDBDialectUtf8mb4

#logging:
#  level:
#    root: info
#    com.blog.blog: debug
#  file:
#    name: log/blog-dev.log
server:
  port: 8080
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql